/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 2abf140bb33b522f398a6ce268b50e80)
interface __BaseEnv_Env {
	R2: R2Bucket;
	LOADER: WorkerLoader;
	BROWSER: Fetcher;
	AI: Ai;
	LINKUP_API_KEY: string;
	GITHUB_TOKEN: string;
	ThinkAgent: DurableObjectNamespace<import("./src/server").ThinkAgent>;
	ResearchAgent: DurableObjectNamespace<import("./src/server").ResearchAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ThinkAgent" | "ResearchAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LINKUP_API_KEY" | "GITHUB_TOKEN">> {}
}
