/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 1433a31e5cb76a9072c58971a117d13f)
interface __BaseEnv_Env {
	R2: R2Bucket;
	LOADER: WorkerLoader;
	BROWSER: Fetcher;
	AI: Ai;
	ThinkAgent: DurableObjectNamespace<import("./src/server").ThinkAgent>;
	ResearchAgent: DurableObjectNamespace<import("./src/server").ResearchAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ThinkAgent" | "ResearchAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
